# Generated by Django 2.2.1 on 2020-08-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_subscriptions', '0001_initial'),
        ('sprint_subscriptions', '0001_initial'),
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.ATTSubscription')),
                ('data_usage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usage.DataUsageRecord')),
                ('sprint_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sprint_subscriptions.SprintSubscription')),
                ('voice_usage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usage.VoiceUsageRecord')),
            ],
        ),
    ]
